// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_roomblue_png);    // assets/roomblue.png
LV_IMG_DECLARE(ui_img_1661332484);    // assets/logo (1).png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
